pipeline:
  agent:
    any:
  tools:
    maven: 'maven' 
  
  stages:
    - stage: "Checkout"
      steps: git "https://github.com/tolux17tech/project-test.git"
    
    - stage: "Test Project Folder"
      steps: 
        script: 
          - dir: "'project'"
            script:
              - sh "mvn clean test"
    
    - stage: "Test Database Folder"
      steps:
        script:
          - dir: "'database'"
            script: 
              - sh "mvn clean test -Dscope=FlywayMigration"
    - stage: "Deploy configuration"
      stages:
        - stage: "mvn install for project"
          steps:
            script:
              - dir: "'project'"
                script: 
                  - sh "mvn clean install"
        - stage: "mvn install for Database"
          steps:
            script:
              - dir: "'database'"
                script: 
                  - sh "mvn clean install"
        - stage: "Test configuration"
          parallel:
            - stage: "Peformance Testing"
              steps:
                script:
                  - dir: "'test'"
                    script:
                      - sh "mvn clean test -Dscope=performance"
                
    
  
