pipeline:
  agent:
    any:
    tools:
      maven: 'maven' 
  
  stages:
    - stage: "Checkout"
      steps: "https://github.com/tolux17tech/project-test.git"
    
   
    - stage: "Build"
      steps: 
      script: 
        - sh "cd project && mvn clean test"
    
    # - stage: "Database"
    #   steps:
    #   script: 
    #     - sh "cd database && mvn clean test -Dscope=FlywayMigration"
    # - stage: "Deploy"
    #   steps: 
    #     -
    # - stage: "Test"
    #   steps: 
    #     -

