pipeline:
  agent:
    any:
  tools:
    maven: 'maven' 
  post:
    success:
      script:
        - "mail bcc: 'my@box.com', body: 'Pipeline Built sucessfully', cc: '', from: '', replyTo: '', subject: 'Success', to: 'my@box.com'"
    failure:
      script:
        - "mail bcc: 'my@box.com', body: 'Pipeline Failed', cc: '', from: '', replyTo: '', subject: 'Failure', to: 'my@box.com'"
  
  stages:
    - stage: "Checkout"
      steps: git "https://github.com/tolux17tech/project-test.git"
    
    - stage: "Test Project Folder"
      steps: 
        script: 
          - dir: "'project'"
            script:
              - sh "mvn clean test"
    
    - stage: "Test Database Folder"
      steps:
        script:
          - dir: "'database'"
            script: 
              - sh "mvn clean test -Dscope=FlywayMigration"
    - stage: "Deploy configuration"
      stages:
        - stage: "mvn install for project"
          steps:
            script:
              - dir: "'project'"
                script: 
                  - sh "mvn clean install"
        - stage: "mvn install for Database"
          steps:
            script:
              - dir: "'database'"
                script: 
                  - sh "mvn clean install"
        - stage: "Test configuration"
          parallel:
            - stage: "Peformance Testing"
              steps:
                script:
                  - dir: "'test'"
                    script:
                      - sh "mvn clean test -Dscope=performance"

            - stage: "Regression Testing"
              steps:
                script:
                  - dir: "'test'"
                    script:
                      - sh "mvn clean test -Dscope=regression; exit 1"

            - stage: "Integration Testing"
              steps:
                script:
                  - dir: "'test'"
                    script:
                      - sh "mvn clean test -Dscope=integration"
                
                
                
    
  
